import {
  WiDaySunny,
  WiDayCloudy,
  WiWindy,
  WiCloudy,
  WiRain,
  WiDayRain,
  WiThunderstorm,
  WiDaySnow,
  WiNightAltRainMix,
  WiNightClear,
  WiNightCloudy,
  WiNightAltRain,
  WiNightAltSnow,
  WiCloudRefresh,
  WiRaindrops,
  WiStrongWind,
  WiDayHaze,
  WiFog,
  WiShowers,
  WiDayShowers,
  WiDayThunderstorm,
  WiRainMix,
  WiDayRainMix,
  WiSnowflakeCold,
  WiSnow,
  WiThermometerExterior,
  WiThermometer,
  WiNightFog,
  WiNightAltThunderstorm,
  WiDirectionUp,
  WiDirectionDown,
  WiSunrise,
  WiSunset,
  WiDaySunnyOvercast
} from 'weather-icons-react';

const WeatherIcons = {
  '1': WiDaySunny,
  '2': WiDaySunnyOvercast,
  '3': WiDaySunnyOvercast,
  '4': WiDayCloudy,
  '5': WiDayHaze,
  '6': WiDayCloudy,
  '7': WiCloudy,
  '8': WiCloudy,
  '11': WiFog,
  '12': WiShowers,
  '13': WiDayRain,
  '14': WiDayShowers,
  '15': WiThunderstorm,
  '16': WiDayThunderstorm,
  '17': WiDayThunderstorm,
  '18': WiRain,
  '19': WiRainMix,
  '20': WiDayRainMix,
  '21': WiDayRainMix,
  '22': WiSnowflakeCold,
  '23': WiDaySnow,
  '24': WiSnowflakeCold,
  '25': WiSnow,
  '26': WiRainMix,
  '29': WiRainMix,
  '30': WiThermometer,
  '31': WiThermometerExterior,
  '32': WiWindy,
  '33': WiNightClear,
  '34': WiNightClear,
  '35': WiNightCloudy,
  '36': WiNightCloudy,
  '37': WiNightFog,
  '38': WiNightCloudy,
  '39': WiNightAltRain,
  '40': WiNightAltRain,
  '41': WiNightAltThunderstorm,
  '42': WiNightAltThunderstorm,
  '43': WiNightAltRainMix,
  '44': WiNightAltSnow,
  'loading': WiCloudRefresh,
  'clouds': WiCloudy,
  'humidity': WiRaindrops,
  'wind': WiStrongWind,
  'max': WiDirectionUp,
  'min': WiDirectionDown,
  'rain': WiRain,
  'snow': WiSnowflakeCold,
  'sunrise': WiSunrise,
  'sunset': WiSunset,
  'default': WiDayCloudy
};

export default WeatherIcons;
